import {
  blazerBelowChestReady,
  blazerBicepsLoose,
  blazerChestReady,
  blazerElbowLoose,
  blazerForearmReady,
  blazerSeatReady,
  blazerWaistReady,
  blazer_armhole_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy blazerMeasurements. */
export const blazerSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.BLAZER,
  subCat: "blazer",
  options: [
    [
      {
        label: "Blazer Length",
        name: "blazer_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Shoulder",
        name: "blazer_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Neck",
        name: "blazer_neck",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Cross Back",
        name: "blazer_cross_back",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Cross Chest",
        name: "blazer_cross_chest",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Chest",
        name: "blazer_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerChestReady],
      },
      {
        label: "Blazer Chest Loosening",
        name: "blazer_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [blazerChestReady],
      },
      {
        label: "Blazer Chest Ready",
        name: "blazer_chest_ready",
        isRequired: false,
        canBeEdited: false,
        formula: blazerChestReady,
      },
    ],
    [
      {
        label: "Blazer Below Chest",
        name: "blazer_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerBelowChestReady],
      },
      {
        label: "Blazer Below Chest Loosening",
        name: "blazer_below_chest_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 0,
        internalFormula: [blazerBelowChestReady],
      },
      {
        label: "Blazer Below Chest Ready",
        name: "blazer_below_chest_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: blazerBelowChestReady,
      },
    ],
    [
      {
        label: "Blazer Waist",
        name: "blazer_waist",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerWaistReady],
      },
      {
        label: "Blazer waist Loosening",
        name: "blazer_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 1,
        defaultCm: 0.5,
        internalFormula: [blazerWaistReady],
      },
      {
        label: "Blazer Waist Ready",
        name: "blazer_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: blazerWaistReady,
      },
    ],
    [
      {
        label: "Blazer Seat",
        name: "blazer_seat",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerSeatReady],
      },
      {
        label: "Blazer seat Loosening",
        name: "blazer_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 1,
        defaultCm: 0.75,
        internalFormula: [blazerSeatReady],
      },
      {
        label: "Blazer seat Ready",
        name: "blazer_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: blazerSeatReady,
      },
    ],
    [
      {
        label: "Blazer Biceps Body",
        name: "blazer_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerBicepsLoose],
      },
      {
        label: "Blazer Biceps Loosening",
        name: "blazer_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [blazerBicepsLoose],
      },
      {
        label: "Blazer Biceps Ready",
        name: "blazer_biceps_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: blazerBicepsLoose,
      },
    ],
    [
      {
        label: "Blazer Elbow Body",
        name: "blazer_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerElbowLoose],
      },
      {
        label: "Blazer Elbow Loosening",
        name: "blazer_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [blazerElbowLoose],
      },
      {
        label: "Blazer Elbow Ready",
        name: "blazer_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: blazerElbowLoose,
      },
    ],
    [
      {
        label: "Blazer Forearm Body",
        name: "blazer_forearm_body",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [blazerForearmReady],
      },
      {
        label: "Blazer Forearm Loosening",
        name: "blazer_forearm_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [blazerForearmReady],
      },
      {
        label: "Blazer Forearm Ready",
        name: "blazer_forearm_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: blazerForearmReady,
      },
    ],
    [
      {
        label: "Blazer Sleeve Length",
        name: "blazer_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Cuff Opening",
        name: "blazer_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Armhole Body",
        name: "blazer_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [blazer_armhole_ready],
      },
      {
        label: "Blazer Armhole loosening",
        name: "blazer_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [blazer_armhole_ready],
      },
      {
        label: "Blazer Armhole Ready",
        name: "blazer_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: blazer_armhole_ready,
      },
    ],
  ],
}
