import {
  indowestern_armhole_ready,
  indowestern_below_chest_ready,
  indowestern_biceps_loose,
  indowestern_chest_ready,
  indowestern_elbow_loose,
  indowestern_forearm_ready,
  indowestern_neck_ready,
  indowestern_seat_ready,
  indowestern_waist_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy indoWesternMeasuerements. */
export const indowesternSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.INDOWESTERN,
  subCat: "indowestern",
  options: [
    [
      {
        label: "Indowestern Length",
        name: "indowestern_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Indowestern Knee Length",
        name: "indowestern_knee_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Indowestern Shoulder",
        name: "indowestern_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Indowestern Cross Back",
        name: "indowestern_cross_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Indowestern Cross Chest",
        name: "indowestern_cross_chest",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Indowestern Neck Body",
        name: "indowestern_neck_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_neck_ready],
      },
      {
        label: "Indowestern Neck Ready",
        name: "indowestern_neck_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: indowestern_neck_ready,
      },
    ],
    [
      {
        label: "Indowestern Chest Body",
        name: "indowestern_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_chest_ready],
      },
      {
        label: "Indowestern Chest Loosening",
        name: "indowestern_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [indowestern_chest_ready],
      },
      {
        label: "Indowestern Chest Ready",
        name: "indowestern_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_chest_ready,
      },
    ],
    [
      {
        label: "Indowestern Below Chest",
        name: "indowestern_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_below_chest_ready],
      },
      {
        label: "Indowestern Below Chest Loosening",
        name: "indowestern_below_chest_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [indowestern_below_chest_ready],
      },
      {
        label: "Indowestern Below Chest Ready",
        name: "indowestern_below_chest_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_below_chest_ready,
      },
    ],
    [
      {
        label: "Indowestern Waist Body",
        name: "indowestern_waist_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_waist_ready],
      },
      {
        label: "Indowestern waist Loosening",
        name: "indowestern_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [indowestern_waist_ready],
      },
      {
        label: "Indowestern waist Ready",
        name: "indowestern_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_waist_ready,
      },
    ],
    [
      {
        label: "Indowestern seat Body",
        name: "indowestern_seat_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_seat_ready],
      },
      {
        label: "Indowestern seat Loosening",
        name: "indowestern_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [indowestern_seat_ready],
      },
      {
        label: "Indowestern seat Ready",
        name: "indowestern_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_seat_ready,
      },
    ],
    [
      {
        label: "Indowestern Biceps Body",
        name: "indowestern_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_biceps_loose],
      },
      {
        label: "Indowestern Biceps Loosening",
        name: "indowestern_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [indowestern_biceps_loose],
      },
      {
        label: "Indowestern Biceps Ready",
        name: "indowestern_biceps_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_biceps_loose,
      },
    ],
    [
      {
        label: "Indowestern Elbow Body",
        name: "indowestern_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_elbow_loose],
      },
      {
        label: "Indowestern Elbow Loosening",
        name: "indowestern_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [indowestern_elbow_loose],
      },
      {
        label: "Indowestern Elbow Ready",
        name: "indowestern_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_elbow_loose,
      },
    ],
    [
      {
        label: "Indowestern Forearm Body",
        name: "indowestern_forearm_body",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [indowestern_forearm_ready],
      },
      {
        label: "Indowestern Forearm Loosening",
        name: "indowestern_forearm_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [indowestern_forearm_ready],
      },
      {
        label: "Indowestern Forearm Ready",
        name: "indowestern_forearm_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: indowestern_forearm_ready,
      },
    ],
    [
      {
        label: "Indowestern Sleeve Length",
        name: "indowestern_sleeve_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Indowestern Cuff opening",
        name: "indowestern_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Indowestern Armhole Body",
        name: "indowestern_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [indowestern_armhole_ready],
      },
      {
        label: "Indowestern Armhole loosening",
        name: "indowestern_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [],
      },
      {
        label: "Indowestern Armhole Ready",
        name: "indowestern_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: indowestern_armhole_ready,
      },
    ],
  ],
}
