import {
  jodhpuriBelowChestReady,
  jodhpuriForearmReady,
  jodhpuri_armhole_ready,
  jodhpuri_biceps_loose,
  jodhpuri_chest_ready,
  jodhpuri_elbow_loose,
  jodhpuri_neck_ready,
  jodhpuri_seat_ready,
  jodhpuri_waist_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy jodhpuriMeasurements. */
export const jodhpuriSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.JODHPURI,
  subCat: "jodhpuri",
  options: [
    [
      {
        label: "Jodhpuri Length",
        name: "jodhpuri_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "jodhpuri Shoulder",
        name: "jodhpuri_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "jodhpuri Cross Back",
        name: "jodhpuri_cross_back",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "jodhpuri Cross Chest",
        name: "jodhpuri_cross_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "jodhpuri Neck Body",
        name: "jodhpuri_neck_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_neck_ready],
      },
      {
        label: "jodhpuri Neck Ready",
        name: "jodhpuri_neck_ready",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: false,
        formula: jodhpuri_neck_ready,
      },
    ],
    [
      {
        label: "jodhpuri Chest",
        name: "jodhpuri_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_chest_ready],
      },
      {
        label: "jodhpuri Chest Loosening",
        name: "jodhpuri_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [jodhpuri_chest_ready],
      },
      {
        label: "jodhpuri Chest Ready",
        name: "jodhpuri_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuri_chest_ready,
      },
    ],
    [
      {
        label: "jodhpuri Below Chest ",
        name: "jodhpuri_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuriBelowChestReady],
      },
      {
        label: "jodhpuri Below Chest Loosening",
        name: "jodhpuri_below_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [jodhpuriBelowChestReady],
      },
      {
        label: "jodhpuri Below Chest Ready",
        name: "jodhpuri_below_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuriBelowChestReady,
      },
    ],
    [
      {
        label: "jodhpuri Waist",
        name: "jodhpuri_waist",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_waist_ready],
      },
      {
        label: "jodhpuri waist Loosening",
        name: "jodhpuri_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [jodhpuri_waist_ready],
      },
      {
        label: "jodhpuri Waist Ready",
        name: "jodhpuri_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuri_waist_ready,
      },
    ],
    [
      {
        label: "jodhpuri Seat",
        name: "jodhpuri_seat",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_seat_ready],
      },
      {
        label: "jodhpuri seat Loosening",
        name: "jodhpuri_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [jodhpuri_seat_ready],
      },
      {
        label: "jodhpuri seat Ready",
        name: "jodhpuri_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuri_seat_ready,
      },
    ],
    [
      {
        label: "jodhpuri Biceps Body",
        name: "jodhpuri_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_biceps_loose],
      },
      {
        label: "jodhpuri Biceps Loosening",
        name: "jodhpuri_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [jodhpuri_biceps_loose],
      },
      {
        label: "jodhpuri Biceps Ready",
        name: "jodhpuri_biceps_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuri_biceps_loose,
      },
    ],
    [
      {
        label: "jodhpuri Elbow Body",
        name: "jodhpuri_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuri_elbow_loose],
      },
      {
        label: "jodhpuri Elbow Loosening",
        name: "jodhpuri_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [jodhpuri_elbow_loose],
      },
      {
        label: "jodhpuri Elbow Ready",
        name: "jodhpuri_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuri_elbow_loose,
      },
    ],
    [
      {
        label: "jodhpuri Forearm Body",
        name: "jodhpuri_forearm_body",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [jodhpuriForearmReady],
      },
      {
        label: "jodhpuri Forearm Loosening",
        name: "jodhpuri_forearm_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [jodhpuriForearmReady],
      },
      {
        label: "jodhpuri Forearm Ready",
        name: "jodhpuri_forearm_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: jodhpuriForearmReady,
      },
    ],
    [
      {
        label: "jodhpuri Sleeve Length",
        name: "jodhpuri_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "jodhpuri Cuff Opening",
        name: "jodhpuri_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Jodhpuri Armhole Body",
        name: "jodhpuri_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [jodhpuri_armhole_ready],
      },
      {
        label: "Jodhpuri Armhole loosening",
        name: "jodhpuri_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [jodhpuri_armhole_ready],
      },
      {
        label: "Jodhpuri Armhole Ready",
        name: "jodhpuri_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: jodhpuri_armhole_ready,
      },
    ],
  ],
}
