import {
  kurta_armhole_ready,
  kurta_back_below_chest,
  kurta_back_chest,
  kurta_back_seat,
  kurta_back_waist,
  kurta_below_chest_ready,
  kurta_biceps_ready,
  kurta_chest_ready,
  kurta_elbow_loose,
  kurta_forearm_ready,
  kurta_front_below_chest,
  kurta_front_half_chest,
  kurta_front_half_seat,
  kurta_front_half_waist,
  kurta_ready_neck,
  kurta_seat_ready,
  kurta_waist_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy kurtaMeasurements. */
export const kurtaSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.KURTA,
  subCat: "kurta",
  options: [
    [
      {
        label: "Kurta Length",
        name: "kurta_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta Knee Length",
        name: "kurta_knee_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta Shoulder",
        name: "kurta_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta Cross Back",
        name: "kurta_cross_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Kurta Cross Chest",
        name: "kurta_cross_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Kurta Body Neck",
        name: "kurta_body_neck",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_ready_neck],
      },
      {
        label: "Kurta Ready Neck",
        name: "kurta_ready_neck",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: false,
        formula: kurta_ready_neck,
      },
    ],
    [
      {
        label: "Kurta Chest Body",
        name: "kurta_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_chest_ready, kurta_front_half_chest, kurta_back_chest],
      },
      {
        label: "Kurta Chest Loosening",
        name: "kurta_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 4,
        internalFormula: [kurta_chest_ready, kurta_front_half_chest, kurta_back_chest],
      },
      {
        label: "Kurta Chest Ready",
        name: "kurta_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_chest_ready,
      },
      {
        label: "Kurta Front Chest",
        name: "kurta_front_half_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_front_half_chest,
        manualUpdateFormula: [kurta_back_chest],
        resetFormula: [kurta_front_half_chest],
      },
      {
        label: "Kurta Back Chest",
        name: "kurta_back_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_back_chest,
        manualUpdateFormula: [kurta_front_half_chest],
        resetFormula: [kurta_back_chest],
      },
    ],
    [
      {
        label: "Kurta Below Chest",
        name: "kurta_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_below_chest_ready, kurta_front_below_chest, kurta_back_below_chest],
      },
      {
        label: "Kurta Below Chest Loosening",
        name: "kurta_below_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurta_below_chest_ready, kurta_front_below_chest, kurta_back_below_chest],
      },
      {
        label: "Kurta Below Chest Ready",
        name: "kurta_below_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_below_chest_ready,
      },
      {
        label: "Kurta Front Below Chest",
        name: "kurta_front_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_front_below_chest,
        manualUpdateFormula: [kurta_back_below_chest],
        resetFormula: [kurta_front_below_chest],
      },
      {
        label: "Kurta Back Below Chest",
        name: "kurta_back_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_back_below_chest,
        manualUpdateFormula: [kurta_front_below_chest],
        resetFormula: [kurta_back_below_chest],
      },
    ],
    [
      {
        label: "Kurta Waist Body",
        name: "kurta_waist_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_waist_ready, kurta_front_half_waist, kurta_back_waist],
      },
      {
        label: "Kurta waist Loosening",
        name: "kurta_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        defaultCm: 0.5,
        internalFormula: [kurta_waist_ready, kurta_front_half_waist, kurta_back_waist],
      },
      {
        label: "Kurta Waist Ready",
        name: "kurta_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_waist_ready,
      },
      {
        label: "Kurta Front waist",
        name: "kurta_front_half_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_front_half_waist,
        manualUpdateFormula: [kurta_back_waist],
        resetFormula: [kurta_front_half_waist],
      },
      {
        label: "Kurta Back Waist",
        name: "kurta_back_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_back_waist,
        manualUpdateFormula: [kurta_front_half_waist],
        resetFormula: [kurta_waist_ready],
      },
    ],
    [
      {
        label: "Kurta Seat Body",
        name: "kurta_seat_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_seat_ready, kurta_front_half_seat, kurta_back_seat],
      },
      {
        label: "Kurta seat Loosening",
        name: "kurta_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        defaultCm: 0.5,
        internalFormula: [kurta_seat_ready, kurta_front_half_seat, kurta_back_seat],
      },
      {
        label: "Kurta Seat Ready",
        name: "kurta_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_seat_ready,
      },
      {
        label: "Kurta Front Seat",
        name: "kurta_front_half_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_front_half_seat,
        manualUpdateFormula: [kurta_back_seat],
        resetFormula: [kurta_front_half_seat],
      },
      {
        label: "Kurta Back Seat",
        name: "kurta_back_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_back_seat,
        manualUpdateFormula: [kurta_front_half_seat],
        resetFormula: [kurta_back_seat],
      },
    ],
    [
      {
        label: "Kurta Biceps Body",
        name: "kurta_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_biceps_ready],
      },
      {
        label: "Kurta Biceps Loosening",
        name: "kurta_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [kurta_biceps_ready],
      },
      {
        label: "Kurta Biceps Ready",
        name: "kurta_biceps_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_biceps_ready,
      },
    ],
    [
      {
        label: "Kurta Elbow Body",
        name: "kurta_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_elbow_loose],
      },
      {
        label: "Kurta Elbow Loosening",
        name: "kurta_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [kurta_elbow_loose],
      },
      {
        label: "Kurta Elbow Ready",
        name: "kurta_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_elbow_loose,
      },
    ],
    [
      {
        label: "Kurta Forearm Body",
        name: "kurta_forearm_body",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurta_forearm_ready],
      },
      {
        label: "Kurta Forearm Loosening",
        name: "kurta_forearm_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurta_forearm_ready],
      },
      {
        label: "Kurta Forearm Ready",
        name: "kurta_forearm_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: kurta_forearm_ready,
      },
    ],
    [
      {
        label: "Kurta Sleeve Length",
        name: "kurta_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta Cuff Opening",
        name: "kurta_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Kurta Armhole Body",
        name: "kurta_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurta_armhole_ready],
      },
      {
        label: "Kurta Armhole loosening",
        name: "kurta_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurta_armhole_ready],
      },
      {
        label: "Kurta Armhole Ready",
        name: "kurta_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurta_armhole_ready,
      },
    ],
  ],
}
