import {
  kurtaShirtArmholeReady,
  kurtaShirtBackBelowChest,
  kurtaShirtBackChestFormula,
  kurtaShirtBackSeat,
  kurtaShirtBackWaist,
  kurtaShirtBelowChestReady,
  kurtaShirtBicepsReady,
  kurtaShirtChestReadyFormula,
  kurtaShirtElbowReady,
  kurtaShirtForearmReady,
  kurtaShirtFromHalfChestFormula,
  kurtaShirtFrontHalfBelowChest,
  kurtaShirtFrontHalfSeat,
  kurtaShirtFrontHalfWaist,
  kurtaShirtSeatReady,
  kurtaShirtWaistReady,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy kurtashirtMeasurementAttributes. */
export const kurtaShirtSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.KURTA_SHIRT,
  subCat: "kurta_shirt",
  options: [
    [
      {
        label: "Kurta - Shirt Length",
        name: "kurta_shirt_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Knee Length",
        name: "knee_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta -Shirt Shoulder",
        name: "kurta_shirt_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Cross Back",
        name: "kurta_shirt_cross_back",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Cross Front",
        name: "kurta_shirt_cross_front",
        role: "roaming_master",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Kurta - Shirt Neck Body",
        name: "kurta_shirt_neck_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Neck Ready",
        name: "kurta_shirt_neck_ready",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Kurta - Shirt Chest Body",
        name: "kurta_shirt_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtChestReadyFormula, kurtaShirtFromHalfChestFormula, kurtaShirtBackChestFormula],
      },
      {
        label: "Kurta - Shirt Chest Loosening",
        name: "kurta_shirt_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [kurtaShirtChestReadyFormula, kurtaShirtFromHalfChestFormula, kurtaShirtBackChestFormula],
      },
      {
        label: "Kurta - Shirt Chest Ready",
        name: "kurta_shirt_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurtaShirtChestReadyFormula,
      },
      {
        label: "Kurta - Shirt Front Half Chest",
        name: "kurta_shirt_front_half_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtFromHalfChestFormula,
        manualUpdateFormula: [kurtaShirtBackChestFormula],
        resetFormula: [kurtaShirtFromHalfChestFormula],
      },
      {
        label: "Kurta - Shirt Back Chest",
        name: "kurta_shirt_back_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtBackChestFormula,
        manualUpdateFormula: [kurtaShirtFromHalfChestFormula],
        resetFormula: [kurtaShirtBackChestFormula],
      },
    ],
    [
      {
        label: "Kurta - Shirt Below Chest",
        name: "kurta_shirt_below_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtBelowChestReady, kurtaShirtFrontHalfBelowChest, kurtaShirtBackBelowChest],
      },
      {
        label: "Kurta - Shirt Below Chest Loosening",
        name: "kurta_shirt_below_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [kurtaShirtBelowChestReady, kurtaShirtFrontHalfBelowChest, kurtaShirtBackBelowChest],
      },
      {
        label: "Kurta - Shirt Below Chest Ready",
        name: "kurta_shirt_below_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurtaShirtBelowChestReady,
      },
      {
        label: "Kurta - Shirt Front Half Below Chest",
        name: "kurta_shirt_front_half_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtFrontHalfBelowChest,
        manualUpdateFormula: [kurtaShirtBackBelowChest],
        resetFormula: [kurtaShirtFrontHalfBelowChest],
      },
      {
        label: "Kurta - Shirt Back Below Chest",
        name: "kurta_shirt_back_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtBackBelowChest,
        manualUpdateFormula: [kurtaShirtFrontHalfBelowChest],
        resetFormula: [kurtaShirtBackBelowChest],
      },
    ],
    [
      {
        label: "Kurta - Shirt Waist Body",
        name: "kurta_shirt_waist_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtWaistReady, kurtaShirtFrontHalfWaist, kurtaShirtBackWaist],
      },
      {
        label: "Kurta - Shirt Waist Loosening",
        name: "kurta_shirt_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [kurtaShirtWaistReady, kurtaShirtFrontHalfWaist, kurtaShirtBackWaist],
      },
      {
        label: "Kurta - Shirt Waist Ready",
        name: "kurta_shirt_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurtaShirtWaistReady,
      },
      {
        label: "Kurta - Shirt Front Half Waist",
        name: "kurta_shirt_front_half_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtFrontHalfWaist,
        manualUpdateFormula: [kurtaShirtBackWaist],
        resetFormula: [kurtaShirtFrontHalfWaist],
      },
      {
        label: "Kurta - Shirt Back Waist",
        name: "kurta_shirt_back_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtBackWaist,
        internalFormula: [kurtaShirtWaistReady],
        manualUpdateFormula: [kurtaShirtFrontHalfWaist],
        resetFormula: [kurtaShirtBackWaist],
      },
    ],
    [
      {
        label: "Kurta - Shirt Seat Body",
        name: "kurta_shirt_seat_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtSeatReady, kurtaShirtFrontHalfSeat, kurtaShirtBackSeat],
      },
      {
        label: "Kurta - Shirt Seat Loosening",
        name: "kurta_shirt_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [kurtaShirtSeatReady, kurtaShirtFrontHalfSeat, kurtaShirtBackSeat],
      },
      {
        label: "Kurta - Shirt Seat Ready",
        name: "kurta_shirt_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
      {
        label: "Kurta - Shirt Front Half Seat",
        name: "kurta_shirt_front_half_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtFrontHalfSeat,
        manualUpdateFormula: [kurtaShirtBackSeat],
        resetFormula: [kurtaShirtFrontHalfSeat],
      },
      {
        label: "Kurta - Shirt Back Seat",
        name: "kurta_shirt_back_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtBackSeat,
        manualUpdateFormula: [kurtaShirtFrontHalfSeat],
        resetFormula: [kurtaShirtBackSeat],
      },
    ],
    [
      {
        label: "Kurta - Shirt Biceps Body",
        name: "kurta_shirt_biceps_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtBicepsReady],
      },
      {
        label: "Kurta - Shirt Biceps Loosening",
        name: "kurta_shirt_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [kurtaShirtBicepsReady],
      },
      {
        label: "Kurta - Shirt Biceps Ready",
        name: "kurta_shirt_biceps_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
    ],
    [
      {
        label: "Kurta - Shirt Elbow Body",
        name: "kurta_shirt_elbow_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtElbowReady],
      },
      {
        label: "Kurta - Shirt Elbow Loosening",
        name: "kurta_shirt_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [kurtaShirtElbowReady],
      },
      {
        label: "Kurta - Shirt Elbow Ready",
        name: "kurta_shirt_elbow_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurtaShirtElbowReady,
      },
    ],
    [
      {
        label: "Kurta - Shirt Forearm Body",
        name: "kurta_shirt_forearm_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [kurtaShirtForearmReady],
      },
      {
        label: "Kurta - Shirt Forearm Loosening",
        name: "kurta_shirt_forearm_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurtaShirtForearmReady],
      },
      {
        label: "Kurta - Shirt Forearm Ready",
        name: "kurta_shirt_forearm_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: kurtaShirtForearmReady,
      },
    ],
    [
      {
        label: "Kurta - Shirt Sleeve length",
        name: "kurta_shirt_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Half Sleeve length",
        name: "kurta_shirt_half_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Half Sleeve opening",
        name: "kurta_shirt_half_sleeve_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Kurta - Shirt Cuffs opening",
        name: "kurta_shirt_cuffs_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Kurta - Shirt Armhole Body",
        name: "kurta_shirt_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurtaShirtArmholeReady],
      },
      {
        label: "Kurta - Shirt Armhole Loosening",
        name: "kurta_shirt_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [kurtaShirtArmholeReady],
      },
      {
        label: "Kurta - Shirt Armhole Ready",
        name: "kurta_shirt_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: kurtaShirtArmholeReady,
      },
    ],
  ],
}
