import {
  sherwani_armhole_ready,
  sherwani_below_chest_ready,
  sherwani_biceps_loose,
  sherwani_chest_ready,
  sherwani_elbow_loose,
  sherwani_forearm_ready,
  sherwani_neck_ready,
  sherwani_seat_ready,
  sherwani_waist_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy sherwaniMeasurements. */
export const sherwaniSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.SHERWANI,
  subCat: "sherwani",
  options: [
    [
      {
        label: "Sherwani Length",
        name: "sherwani_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Sherwani Knee Length",
        name: "sherwani_knee_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Sherwani Shoulder",
        name: "sherwani_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Sherwani Cross Back",
        name: "sherwani_cross_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Sherwani Cross Chest",
        name: "sherwani_cross_chest",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Sherwani Neck Body",
        name: "sherwani_neck_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_neck_ready],
      },
      {
        label: "Sherwani Neck Ready",
        name: "sherwani_neck_ready",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: false,
        formula: sherwani_neck_ready,
      },
    ],
    [
      {
        label: "Sherwani Chest Body",
        name: "sherwani_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_chest_ready],
      },
      {
        label: "Sherwani Chest Loosening",
        name: "sherwani_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [sherwani_chest_ready],
      },
      {
        label: "Sherwani Chest Ready",
        name: "sherwani_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_chest_ready,
      },
    ],
    [
      {
        label: "Sherwani Below Chest",
        name: "sherwani_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_below_chest_ready],
      },
      {
        label: "Sherwani Below Chest Loosening",
        name: "sherwani_below_chest_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [sherwani_below_chest_ready],
      },
      {
        label: "Sherwani Below Chest Ready",
        name: "sherwani_below_chest_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_below_chest_ready,
      },
    ],
    [
      {
        label: "Sherwani Waist Body",
        name: "sherwani_waist_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_waist_ready],
      },
      {
        label: "Sherwani Waist Loosening",
        name: "sherwani_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [sherwani_waist_ready],
      },
      {
        label: "Sherwani Waist Ready",
        name: "sherwani_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_waist_ready,
      },
    ],
    [
      {
        label: "Sherwani Seat Body",
        name: "sherwani_seat_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_seat_ready],
      },
      {
        label: "Sherwani Seat Loosening",
        name: "sherwani_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [sherwani_seat_ready],
      },
      {
        label: "Sherwani Seat Ready",
        name: "sherwani_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_seat_ready,
      },
    ],
    [
      {
        label: "Sherwani Biceps Body",
        name: "sherwani_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_biceps_loose],
      },
      {
        label: "Sherwani Biceps Loosening",
        name: "sherwani_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [sherwani_biceps_loose],
      },
      {
        label: "Sherwani Biceps Ready",
        name: "sherwani_biceps_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_biceps_loose,
      },
    ],
    [
      {
        label: "Sherwani Elbow Body",
        name: "sherwani_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_elbow_loose],
      },
      {
        label: "Sherwani Elbow Loosening",
        name: "sherwani_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [sherwani_elbow_loose],
      },
      {
        label: "Sherwani Elbow Ready",
        name: "sherwani_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_elbow_loose,
      },
    ],
    [
      {
        label: "Sherwani Forearm Body",
        name: "sherwani_forearm_body",
        role: "personal_stylis",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [sherwani_forearm_ready],
      },
      {
        label: "Sherwani Forearm Loosening",
        name: "sherwani_forearm_loosening",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [sherwani_forearm_ready],
      },
      {
        label: "Sherwani Forearm Ready",
        name: "sherwani_forearm_ready",
        role: "personal_stylis",
        isRequired: false,
        canBeEdited: false,
        formula: sherwani_forearm_ready,
      },
    ],
    [
      {
        label: "Sherwani Sleeve Length",
        name: "sherwani_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Sherwani Cuff Opening",
        name: "sherwani_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Sherwani Armhole Body",
        name: "sherwani_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [sherwani_armhole_ready],
      },
      {
        label: "Sherwani Armhole Loosening",
        name: "sherwani_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [sherwani_armhole_ready],
      },
      {
        label: "Sherwani Armhole Ready",
        name: "sherwani_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: sherwani_armhole_ready,
      },
    ],
  ],
}
