import {
  armhole_ready,
  below_chest_ready,
  outShirtLengthFormula,
  shirtBackChestFormula,
  shirtBackSeat,
  shirtBackWaist,
  shirtBicepsReady,
  shirtChestReadyFormula,
  shirtElbowReady,
  shirtForearmReady,
  shirtFromHalfChestFormula,
  shirtFrontHalfSeat,
  shirtFrontHalfWaist,
  shirtSeatReady,
  shirtWaistReady,
  shirt_back_below_chest,
  shirt_front_half_below_chest,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy shirtMeasurementAttributes. */
export const shirtSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.SHIRT,
  subCat: "full_shirt",
  options: [
    [
      {
        label: "In Shirt Length",
        name: "in_shirt_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [outShirtLengthFormula],
      },
      {
        label: "Out Shirt Length",
        name: "out_shirt_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: outShirtLengthFormula,
        manualUpdateFormula: ["out_shirt_length"],
        resetFormula: [outShirtLengthFormula],
      },
      {
        label: "Shirt Shoulder",
        name: "shirt_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Neck",
        name: "shirt_neck",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Cross Back",
        name: "shirt_cross_back",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Cross Front",
        name: "cross_chest",
        role: "roaming_master",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Shirt Chest Body",
        name: "shirt_chest_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtChestReadyFormula, shirtFromHalfChestFormula, shirtBackChestFormula],
      },
      {
        label: "Shirt Chest Loosening",
        name: "shirt_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [shirtChestReadyFormula, shirtFromHalfChestFormula, shirtBackChestFormula],
      },
      {
        label: "Shirt Chest Ready",
        name: "shirt_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: shirtChestReadyFormula,
      },
      {
        label: "Shirt Front Half Chest",
        name: "shirt_from_half_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtFromHalfChestFormula,
        manualUpdateFormula: [shirtBackChestFormula],
        resetFormula: [shirtFromHalfChestFormula],
      },
      {
        label: "Shirt Back Chest",
        name: "shirt_back_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtBackChestFormula,
        manualUpdateFormula: [shirtFromHalfChestFormula],
        resetFormula: [shirtBackChestFormula],
      },
    ],
    [
      {
        label: "Shirt Below Chest",
        name: "shirt_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [below_chest_ready, shirt_front_half_below_chest, shirt_back_below_chest],
      },
      {
        label: "Shirt Below Chest Loosening",
        name: "below_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [below_chest_ready, shirt_front_half_below_chest, shirt_back_below_chest],
      },
      {
        label: "Shirt Below Chest Ready",
        name: "below_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: below_chest_ready,
      },
      {
        label: "Shirt Front Below Chest",
        name: "shirt_front_half_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirt_front_half_below_chest,
        manualUpdateFormula: [shirt_back_below_chest],
        resetFormula: [shirt_front_half_below_chest],
      },
      {
        label: "Shirt Back Below Chest",
        name: "shirt_back_below_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirt_back_below_chest,
        manualUpdateFormula: [shirt_front_half_below_chest],
        resetFormula: [shirt_back_below_chest],
      },
    ],
    [
      {
        label: "Shirt Waist Body",
        name: "shirt_waist_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtWaistReady, shirtFrontHalfWaist, shirtBackWaist],
      },
      {
        label: "Shirt Waist Loosening",
        name: "shirt_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [shirtWaistReady, shirtFrontHalfWaist, shirtBackWaist],
      },
      {
        label: "Shirt Waist Ready",
        name: "shirt_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: shirtWaistReady,
      },
      {
        label: "Shirt Front Half Waist",
        name: "shirt_front_half_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtFrontHalfWaist,
        manualUpdateFormula: [shirtBackWaist],
        resetFormula: [shirtFrontHalfWaist],
      },
      {
        label: "Shirt Back Waist",
        name: "shirt_back_waist",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtBackWaist,
        internalFormula: [shirtWaistReady],
        manualUpdateFormula: [shirtFrontHalfWaist],
        resetFormula: [shirtBackWaist],
      },
    ],
    [
      {
        label: "Shirt Seat Body",
        name: "shirt_seat_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtSeatReady, shirtFrontHalfSeat, shirtBackSeat],
      },
      {
        label: "Shirt Seat Loosening",
        name: "shirt_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [shirtSeatReady, shirtFrontHalfSeat, shirtBackSeat],
      },
      {
        label: "Shirt Seat Ready",
        name: "shirt_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
      {
        label: "Shirt Front Half Seat",
        name: "shirt_front_half_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtFrontHalfSeat,
        manualUpdateFormula: [shirtBackSeat],
        resetFormula: [shirtFrontHalfSeat],
      },
      {
        label: "Shirt Back Seat",
        name: "shirt_back_seat",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: shirtBackSeat,
        manualUpdateFormula: [shirtFrontHalfSeat],
        resetFormula: [shirtBackSeat],
      },
    ],
    [
      {
        label: "Shirt Biceps Body",
        name: "shirt_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtBicepsReady],
      },
      {
        label: "Shirt Biceps Loosening",
        name: "shirt_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [shirtBicepsReady],
      },
      {
        label: "Shirt Biceps Ready",
        name: "shirt_biceps_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
    ],
    [
      {
        label: "Shirt Elbow Body",
        name: "shirt_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtElbowReady],
      },
      {
        label: "Shirt Elbow Loosening",
        name: "shirt_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [shirtElbowReady],
      },
      {
        label: "Shirt Elbow Ready",
        name: "shirt_elbow_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: shirtElbowReady,
      },
    ],
    [
      {
        label: "Shirt Forearm Body",
        name: "forearm_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [shirtForearmReady],
      },
      {
        label: "Shirt Forearm Loosening",
        name: "forearm_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [shirtForearmReady],
      },
      {
        label: "Shirt Forearm Ready",
        name: "forearm_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: shirtForearmReady,
      },
    ],
    [
      {
        label: "Shirt Sleeve Length",
        name: "shirt_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Half Sleeve Length",
        name: "shirt_half_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Half Sleeve Opening",
        name: "shirt_half_sleeve_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Shirt Cuff Opening",
        name: "cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Shirt Armhole Body",
        name: "armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [armhole_ready],
      },
      {
        label: "Shirt Armhole Loosening",
        name: "armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [armhole_ready],
      },
      {
        label: "Shirt Armhole Ready",
        name: "armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: armhole_ready,
      },
    ],
  ],
}
