import {
  suit_armhole_ready,
  suit_below_chest_ready,
  suit_biceps_loose,
  suit_chest_ready,
  suit_elbow_loose,
  suit_forearm_ready,
  suit_seat_ready,
  suit_trouser_back_tummy_to_back,
  suit_trouser_calf_loose,
  suit_trouser_knee_loose,
  suit_trouser_thigh_loose,
  suit_waist_ready,
} from "../legacy-internal-formulas"

import { MEASUREMENT_CATEGORIES } from "@/config/measurement-categories"
import type { MeasurementGarmentSchema } from "../field-types"

/** Port of legacy suitMeasurements. */
export const suitSchema: MeasurementGarmentSchema = {
  catId: MEASUREMENT_CATEGORIES.SUIT,
  subCat: "two_piece_suit",
  options: [
    [
      {
        label: "Blazer Length",
        name: "suit_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Shoulder",
        name: "suit_shoulder",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Neck",
        name: "suit_neck",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Cross Back",
        name: "suit_cross_back",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Cross Chest",
        name: "suit_cross_chest",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Chest",
        name: "suit_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_chest_ready],
      },
      {
        label: "Blazer Chest Loosening",
        name: "suit_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [suit_chest_ready],
      },
      {
        label: "Blazer Chest Ready",
        name: "suit_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
    ],
    [
      {
        label: "Blazer Below Chest",
        name: "suit_below_chest",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_below_chest_ready],
      },
      {
        label: "Blazer Below Chest Loosening",
        name: "suit_below_chest_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_below_chest_ready],
      },
      {
        label: "Blazer Below Chest Ready",
        name: "suit_below_chest_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: suit_below_chest_ready,
      },
    ],
    [
      {
        label: "Blazer Waist",
        name: "suit_waist",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_waist_ready],
      },
      {
        label: "Blazer waist Loosening",
        name: "suit_waist_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 1,
        defaultCm: 0.5,
        internalFormula: [suit_waist_ready],
      },
      {
        label: "Blazer Waist Ready",
        name: "suit_waist_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
    ],
    [
      {
        label: "Blazer Seat",
        name: "suit_seat",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_seat_ready],
      },
      {
        label: "Blazer seat Loosening",
        name: "suit_seat_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 1,
        defaultCm: 0.75,
        internalFormula: [suit_seat_ready],
      },
      {
        label: "Blazer seat Ready",
        name: "suit_seat_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Biceps Body",
        name: "suit_biceps_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_biceps_loose],
      },
      {
        label: "Blazer Biceps Loosening",
        name: "suit_biceps_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.5,
        internalFormula: [suit_biceps_loose],
      },
      {
        label: "Blazer Biceps Ready",
        name: "suit_biceps_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Elbow Body",
        name: "suit_elbow_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_elbow_loose],
      },
      {
        label: "Blazer Elbow Loosening",
        name: "suit_elbow_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        defaultCm: 0.75,
        internalFormula: [suit_elbow_loose],
      },
      {
        label: "Blazer Elbow Ready",
        name: "suit_elbow_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Forearm Body",
        name: "suit_forearm_body",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_forearm_ready],
      },
      {
        label: "Blazer Forearm Loosening",
        name: "suit_forearm_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_forearm_ready],
      },
      {
        label: "Blazer Forearm Ready",
        name: "suit_forearm_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: suit_forearm_ready,
      },
    ],
    [
      {
        label: "Blazer Sleeve Length",
        name: "suit_sleeve_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Blazer Cuff Opening",
        name: "suit_cuff_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Blazer Armhole Body",
        name: "suit_armhole_body",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_armhole_ready],
      },
      {
        label: "Blazer Armhole loosening",
        name: "suit_armhole_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_armhole_ready],
      },
      {
        label: "Blazer Armhole Ready",
        name: "suit_armhole_ready",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        formula: suit_armhole_ready,
      },
    ],
    [
      {
        label: "Trouser Length",
        name: "suit_trouser_length",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
      {
        label: "Trouser Front Length",
        name: "suit_trouser_front_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
      {
        label: "Trouser Back Length",
        name: "suit_trouser_back_length",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Waist",
        name: "suit_trouser_waist",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Seat",
        name: "suit_trouser_seat",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Thigh Body",
        name: "suit_trouser_thigh_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_trouser_thigh_loose],
      },
      {
        label: "Trouser Thigh Loosening",
        name: "suit_trouser_thigh_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 2,
        internalFormula: [suit_trouser_thigh_loose],
      },
      {
        label: "Trouser Thigh Ready",
        name: "suit_trouser_thigh_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
    ],
    [
      {
        label: "Trouser Knee Body",
        name: "suit_trouser_knee_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_trouser_knee_loose],
      },
      {
        label: "Trouser Knee Loosening",
        name: "suit_trouser_knee_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 3,
        internalFormula: [suit_trouser_knee_loose],
      },
      {
        label: "Trouser Knee Ready",
        name: "suit_trouser_knee_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
      },
      {
        label: "Trouser Knee Down",
        name: "suit_trouser_knee_down",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Calf Body",
        name: "suit_trouser_calf_tight",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
        internalFormula: [suit_trouser_calf_loose],
      },
      {
        label: "Trouser Calf Loosening",
        name: "suit_trouser_calf_loosening",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        defaultInch: 1,
        defaultCm: 0.75,
        internalFormula: [suit_trouser_calf_loose],
      },
      {
        label: "Trouser Calf Ready",
        name: "suit_trouser_calf_loose",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Leg Opening",
        name: "suit_trouser_leg_opening",
        role: "personal_stylist",
        isRequired: true,
        canBeEdited: true,
      },
    ],
    [
      {
        label: "Trouser Tummy to back",
        name: "suit_trouser_tummy_to_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_trouser_back_tummy_to_back],
      },
      {
        label: "Trouser Crotch Front",
        name: "suit_trouser_front_to_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: true,
        internalFormula: [suit_trouser_back_tummy_to_back],
      },
      {
        label: "Trouser Crotch Back",
        name: "suit_trouser_back_tummy_to_back",
        role: "personal_stylist",
        isRequired: false,
        canBeEdited: false,
        formula: suit_trouser_back_tummy_to_back,
      },
    ],
  ],
}
