import type { AnalyticsItem } from "@/lib/apollo/queries/analytics"

function labelOf(item: AnalyticsItem) {
  return item.label?.toLowerCase() ?? ""
}

export function filterByIncludes(
  items: AnalyticsItem[],
  key: string
): AnalyticsItem[] {
  const needle = key.toLowerCase()
  return items.filter((item) => labelOf(item).includes(needle))
}

export function partitionUsers(items: AnalyticsItem[]) {
  const filterUserItems = (key: string) => {
    if (key === "Non Customer Stylist:") {
      return items.filter((item) => {
        const label = labelOf(item)
        return (
          label.includes("non customer stylist") ||
          label === "without non customer stylist"
        )
      })
    }
    return filterByIncludes(items, key)
  }

  return {
    totalCustomers: filterUserItems("Customers"),
    totalNonCustomers: filterUserItems("Non Customer"),
    totalCount: filterUserItems("Total Count"),
    statusCustomers: filterUserItems("Status:"),
    statusNonCustomers: filterUserItems("N/C Status:"),
    customersStylist: filterUserItems("Customer Stylist:"),
    nonCustomersStylist: filterUserItems("Non Customer Stylist:"),
    withOutCCmissed: filterUserItems("CC Missed"),
    withOutCCToday: filterUserItems("CC Today"),
  }
}

export function partitionLeads(items: AnalyticsItem[]) {
  const filterLeadsItems = (key: string) => {
    const normalizedKey = key.trim().toLowerCase()
    return items.filter((item) => {
      const label = labelOf(item)
      if (!label) return false
      if (normalizedKey === "stylist:") {
        return label.startsWith("stylist:") || label === "without stylist"
      }
      if (normalizedKey === "generated by stylist:") {
        return (
          label.startsWith("generated by stylist:") ||
          label === "without generated by stylist"
        )
      }
      if (normalizedKey === "follow up") {
        return (
          label.includes("followup missed") || label.includes("followup today")
        )
      }
      return label.includes(normalizedKey)
    })
  }

  return {
    totalLeads: filterLeadsItems("Leads"),
    sourceLeads: filterLeadsItems("Source:"),
    statusLeads: filterLeadsItems("Status:"),
    stylistScheduled: filterLeadsItems("Stylist:"),
    followUpLeads: filterLeadsItems("Follow Up"),
    occasionLead: filterLeadsItems("Occasion:"),
    generatedByLead: filterLeadsItems("Generated By Stylist:"),
  }
}

export function partitionCif(items: AnalyticsItem[]) {
  const filterCifItems = (key: string) =>
    items.filter((item) => {
      const label = labelOf(item)
      if (key === "Stylist:") {
        return label.startsWith("stylist:") || label === "without stylist"
      }
      if (key === "Studio:") return label.startsWith("studio:")
      if (key === "Occasion:") {
        return label.startsWith("occasion:") || label === "without occasion"
      }
      if (key === "Source:") {
        return label.startsWith("source:") || label === "without source"
      }
      if (key === "Follow Up") {
        return (
          label.includes("followup missed") || label.includes("followup today")
        )
      }
      return label.includes(key.toLowerCase())
    })

  return {
    allCifAnalytics: items.filter((item) => item.label !== "CIF"),
    stylistCif: filterCifItems("Stylist:"),
    statusCif: filterCifItems("Status:"),
    followUpCif: filterCifItems("Follow Up"),
    occasionCif: filterCifItems("Occasion:"),
    sourceCif: filterCifItems("Source:"),
    studioOrdersCif: filterCifItems("Studio:"),
  }
}

export function partitionOrders(items: AnalyticsItem[]) {
  return {
    studioOrders: filterByIncludes(items, "Studio:"),
    stylistOrders: filterByIncludes(items, "Stylist:"),
    sourceOrders: filterByIncludes(items, "Source:"),
    productOrders: filterByIncludes(items, "Product:"),
    ocassionOrders: filterByIncludes(items, "Occasion:"),
    totalOrders: filterByIncludes(items, "Total Order"),
  }
}

export function partitionEmb(items: AnalyticsItem[]) {
  const filterOrderItems = (key: string) =>
    items.filter((item) => {
      if (!item?.label) return false
      if (
        key === "Status:" &&
        (item.label.startsWith("Status:") || item.label === "Without Status")
      ) {
        return true
      }
      if (
        key === "Marking Status:" &&
        (item.label.startsWith("Marking Status:") ||
          item.label === "Without Marking Status")
      ) {
        return true
      }
      if (
        key === "Approval Status:" &&
        (item.label.startsWith("Approval Status:") ||
          item.label === "Without Approval Status")
      ) {
        return true
      }
      if (
        key === "Product:" &&
        (item.label.startsWith("Product:") || item.label === "Without Product")
      ) {
        return true
      }
      if (
        key === "Work Type:" &&
        (item.label.startsWith("Work Type:") ||
          item.label === "Without Work Type")
      ) {
        return true
      }
      if (
        key === "Duration Range:" &&
        item.label.startsWith("Duration Range:")
      ) {
        return true
      }
      if (
        (key === "Total Orders with EMB" ||
          key === "Total Embroidery Amount" ||
          key === "Zero Value Embroideries" ||
          key === "Average Duration") &&
        item.label === key
      ) {
        return true
      }
      return false
    })

  return {
    embWorkTypeOrders: filterOrderItems("Work Type:"),
    embMarkingStatusOrders: filterOrderItems("Marking Status:"),
    embStatusOrders: filterOrderItems("Status:"),
    embApprovalStatusOrders: filterOrderItems("Approval Status:"),
    productEmbOrders: filterOrderItems("Product:"),
    totalEmbCount: filterOrderItems("Total Orders with EMB"),
    totalEmbAmount: filterOrderItems("Total Embroidery Amount"),
    zeroValueEmb: filterOrderItems("Zero Value Embroideries"),
    embDurationRangeOrders: filterOrderItems("Duration Range:"),
    avgDuration: filterOrderItems("Average Duration"),
  }
}

export function partitionReceipts(items: AnalyticsItem[]) {
  return {
    totalNoOfPayments: filterByIncludes(items, "Total Payments"),
    paymentMode: filterByIncludes(items, "PaymentMode:"),
  }
}

export function partitionAppointments(items: AnalyticsItem[]) {
  const filterAppointmentItems = (key: string) =>
    items.filter((item) => {
      const label = labelOf(item)
      if (key === "Stylist:") {
        return label.startsWith("stylist:") || label === "without stylist"
      }
      if (key === "Appointment Created") {
        return (
          label.includes("appointment created") ||
          label.includes("stylist created")
        )
      }
      if (key === "Appointment Scheduled") {
        return (
          label.includes("appointment scheduled") ||
          label.includes("stylist scheduled")
        )
      }
      return label.includes(key.toLowerCase())
    })

  return {
    appointmentCreated: filterAppointmentItems("Appointment Created"),
    appointmentScheduled: filterAppointmentItems("Appointment Scheduled"),
    stylistScheduled: filterAppointmentItems("Stylist Scheduled"),
    stylistCreated: filterAppointmentItems("Stylist Created"),
  }
}

export function partitionQc(items: AnalyticsItem[]) {
  const filterQcItems = (key: string) =>
    items.filter((item) => {
      const label = labelOf(item)
      if (!label) return false
      if (key === "Stylist") {
        return label.startsWith("stylist:") || label === "without stylist"
      }
      return label.includes(key.toLowerCase())
    })

  return {
    totalQcAnalytics: filterQcItems("Total Quality Checks"),
    stylistQcAnalytics: filterQcItems("Stylist"),
  }
}

export function partitionTrial(items: AnalyticsItem[]) {
  const filterTrialItems = (key: string) =>
    items.filter((item) => {
      const label = labelOf(item)
      if (!label) return false
      if (key === "Stylist") {
        return label.startsWith("stylist:") || label === "without stylist"
      }
      return label.includes(key.toLowerCase())
    })

  return {
    totalTrials: filterTrialItems("Total Trials"),
    stylistTrial: filterTrialItems("Stylist"),
  }
}

export function colorForLabel(label: string): string {
  const palette = [
    "oklch(0.55 0.18 250)",
    "oklch(0.6 0.16 145)",
    "oklch(0.65 0.15 85)",
    "oklch(0.58 0.18 25)",
    "oklch(0.55 0.14 310)",
    "oklch(0.5 0.12 200)",
    "oklch(0.62 0.14 40)",
    "oklch(0.48 0.1 280)",
  ]
  let hash = 0
  for (let i = 0; i < label.length; i++) {
    hash = (hash * 31 + label.charCodeAt(i)) >>> 0
  }
  return palette[hash % palette.length]
}
