"use client"

import { useEffect, useId, useMemo, useRef, useState } from "react"
import { CheckIcon, ChevronsUpDownIcon } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { ScrollArea } from "@/components/ui/scroll-area"
import type { StylistOption } from "@/lib/apollo/queries/stylists"
import { cn } from "@/lib/utils"

type StylistSearchSelectProps = {
  /** Omit or pass empty string to hide the field label. */
  label?: string
  id?: string
  stylists: StylistOption[]
  value: string
  onChange: (stylistId: string) => void
  loading?: boolean
  disabled?: boolean
}

/**
 * Single-select stylist picker with a locally anchored dropdown (no portal),
 * so it stays attached on long scrolling forms (lead Generated by / Credit to).
 */
export function StylistSearchSelect({
  label,
  id: idProp,
  stylists,
  value,
  onChange,
  loading = false,
  disabled = false,
}: StylistSearchSelectProps) {
  const reactId = useId()
  const id = idProp || reactId
  const rootRef = useRef<HTMLDivElement>(null)
  const searchRef = useRef<HTMLInputElement>(null)
  const [open, setOpen] = useState(false)
  const [search, setSearch] = useState("")
  // Apollo `loading` differs SSR vs client — defer until mounted to avoid hydration mismatch.
  const [mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
  }, [])
  const showLoading = mounted && loading

  const selected = useMemo(
    () => stylists.find((s) => s._id === value) ?? null,
    [stylists, value]
  )

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase()
    if (!q) return stylists
    return stylists.filter((s) => {
      const haystack = [s.name, s.email, s.phone, s._id]
        .filter(Boolean)
        .join(" ")
        .toLowerCase()
      return haystack.includes(q)
    })
  }, [stylists, search])

  useEffect(() => {
    if (!open) return
    const onPointerDown = (event: MouseEvent) => {
      const target = event.target as Node | null
      if (target && rootRef.current && !rootRef.current.contains(target)) {
        setOpen(false)
      }
    }
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setOpen(false)
    }
    document.addEventListener("mousedown", onPointerDown)
    document.addEventListener("keydown", onKeyDown)
    return () => {
      document.removeEventListener("mousedown", onPointerDown)
      document.removeEventListener("keydown", onKeyDown)
    }
  }, [open])

  useEffect(() => {
    if (!open) return
    const frame = requestAnimationFrame(() => {
      searchRef.current?.focus()
    })
    return () => cancelAnimationFrame(frame)
  }, [open])

  return (
    <div ref={rootRef} className="relative flex min-w-0 flex-col gap-1.5">
      {label ? (
        <Label htmlFor={id} className="text-muted-foreground text-xs font-normal">
          {label}
        </Label>
      ) : null}

      <button
        id={id}
        type="button"
        aria-label={label || "Select stylist"}
        aria-expanded={open}
        aria-haspopup="listbox"
        disabled={disabled || showLoading}
        onClick={() => {
          setOpen((prev) => {
            const next = !prev
            if (next) setSearch("")
            return next
          })
        }}
        className={cn(
          "border-input flex h-8 w-full items-center justify-between gap-2 rounded-lg border bg-transparent px-2.5 text-sm outline-none",
          "focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50",
          "disabled:cursor-not-allowed disabled:opacity-50"
        )}
      >
        <span className="truncate text-left">
          {showLoading
            ? "Loading stylists…"
            : selected?.name || selected?.email || "Select stylist"}
        </span>
        <ChevronsUpDownIcon className="size-3.5 shrink-0 opacity-50" />
      </button>

      {open ? (
        <div
          className={cn(
            "bg-popover text-popover-foreground absolute top-full right-0 left-0 z-50 mt-1",
            "min-w-[240px] overflow-hidden rounded-lg border shadow-md"
          )}
          role="listbox"
          aria-label={label || "Select stylist"}
        >
          <div className="border-b p-2">
            <Input
              ref={searchRef}
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search stylist…"
              className="h-8"
            />
          </div>
          <ScrollArea className="h-52">
            <div className="p-1">
              {filtered.length === 0 ? (
                <p className="text-muted-foreground px-2 py-3 text-sm">
                  No stylist found.
                </p>
              ) : (
                filtered.map((stylist) => (
                  <button
                    key={stylist._id}
                    type="button"
                    role="option"
                    aria-selected={stylist._id === value}
                    className={cn(
                      "hover:bg-accent hover:text-accent-foreground flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-sm",
                      stylist._id === value && "bg-accent"
                    )}
                    onClick={() => {
                      onChange(stylist._id)
                      setOpen(false)
                    }}
                  >
                    <span className="min-w-0 flex-1 truncate text-left">
                      {stylist.name || stylist.email || stylist._id}
                    </span>
                    <CheckIcon
                      className={cn(
                        "size-4 shrink-0",
                        stylist._id === value ? "opacity-100" : "opacity-0"
                      )}
                    />
                  </button>
                ))
              )}
            </div>
          </ScrollArea>
          {value ? (
            <div className="border-t p-1">
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="w-full justify-start"
                onClick={() => {
                  onChange("")
                  setOpen(false)
                }}
              >
                Clear stylist
              </Button>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  )
}
