"use client"

import { useMemo, useState } from "react"

import { AnalyticsCategoryList } from "@/components/analytics/analytics-category-list"
import { AnalyticsKpiCard } from "@/components/analytics/analytics-kpi-card"
import { AnalyticsSectionCard } from "@/components/analytics/analytics-section-card"
import { AnalyticsTabs } from "@/components/analytics/analytics-tabs"
import { useAnalyticsDomain } from "@/hooks/use-analytics-domain"
import { partitionLeads } from "@/lib/analytics/partition"
import {
  GET_LEADS_DASHBOARD_DATA,
  GET_LEADS_DASHBOARD_DRILL_DOWN_DATA,
} from "@/lib/apollo/queries/analytics"

type Props = {
  searchParams: URLSearchParams
  defaultPersonalStylistId?: string | null
}

export function LeadAnalyticsSection({
  searchParams,
  defaultPersonalStylistId,
}: Props) {
  const [tab, setTab] = useState("status")
  const { partitioned, loading, error, items, openDrillDown, drill } =
    useAnalyticsDomain({
      summaryDocument: GET_LEADS_DASHBOARD_DATA,
      summaryAnalyticsPath: "getLeadsDashboardData.analytics",
      drillDocument: GET_LEADS_DASHBOARD_DRILL_DOWN_DATA,
      drillRootField: "getLeadsDashboardDrillDownData",
      searchParams,
      defaultPersonalStylistId,
      partition: partitionLeads,
    })

  const listItems = useMemo(() => {
    switch (tab) {
      case "source":
        return partitioned.sourceLeads
      case "credited":
        return partitioned.stylistScheduled
      case "generated":
        return partitioned.generatedByLead
      case "followup":
        return partitioned.followUpLeads
      case "occasion":
        return partitioned.occasionLead
      default:
        return partitioned.statusLeads
    }
  }, [tab, partitioned])

  return (
    <AnalyticsSectionCard
      title="Lead Analytics"
      loading={loading}
      error={error}
      empty={!loading && !error && items.length === 0}
    >
      <div className="mb-4 grid grid-cols-2 gap-3 md:grid-cols-4">
        {partitioned.totalLeads.map((item) => (
          <AnalyticsKpiCard
            key={item.label}
            subTitle={item.label}
            title={item.value}
          />
        ))}
      </div>
      <AnalyticsTabs
        tabs={[
          { id: "status", label: "Status" },
          { id: "source", label: "Source" },
          { id: "credited", label: "Credited Stylist" },
          { id: "generated", label: "Generated By" },
          { id: "followup", label: "Follow Up" },
          { id: "occasion", label: "Occasion" },
        ]}
        value={tab}
        onChange={setTab}
      />
      <AnalyticsCategoryList
        items={listItems}
        onView={openDrillDown}
        drill={drill}
      />
    </AnalyticsSectionCard>
  )
}
